"""initial schema

Revision ID: 63eee2fbb8ad
Revises: 
Create Date: 2026-09-09 14:19:04.217399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63eee2fbb8ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('banners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('link_url', sa.String(length=255), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.CheckConstraint('status IN (0,1)', name='ck_banners_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_banners_status_sort', 'banners', ['status', 'sort'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.CheckConstraint('status IN (0,1)', name='ck_cases_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cases_status_sort', 'cases', ['status', 'sort'], unique=False)
    op.create_table('news_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.CheckConstraint('status IN (0,1)', name='ck_nc_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nc_status', 'news_categories', ['status'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.CheckConstraint('status IN (0,1)', name='ck_pc_status'),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pc_parent_id', 'product_categories', ['parent_id'], unique=False)
    op.create_index('ix_pc_status', 'product_categories', ['status'], unique=False)
    op.create_table('product_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.CheckConstraint('status IN (0,1)', name='ck_ps_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ps_status', 'product_series', ['status'], unique=False)
    op.create_table('recruit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.CheckConstraint("category IN ('social','campus')", name='ck_recruit_category'),
    sa.CheckConstraint('status IN (0,1)', name='ck_recruit_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recruit_status_category_sort', 'recruit', ['status', 'category', 'sort'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('status IN (0,1)', name='ck_news_status'),
    sa.ForeignKeyConstraint(['category_id'], ['news_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_cat_status_pub', 'news', ['category_id', 'status', 'published_at'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=50), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('style', sa.String(length=50), nullable=True),
    sa.Column('applicable_space', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('gallery', sa.Text(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('status IN (0,1)', name='ck_products_status'),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['series_id'], ['product_series.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_series_category_status', 'products', ['series_id', 'category_id', 'status'], unique=False)
    op.create_index('ix_products_sort', 'products', ['sort'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permissions_rp')
    )
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_index('ix_rp_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('real_name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('status IN (0,1)', name='ck_users_status'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('reply', sa.Text(), nullable=True),
    sa.Column('handler_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("type IN ('message','inquiry')", name='ck_messages_type'),
    sa.CheckConstraint('status IN (0,1)', name='ck_messages_status'),
    sa.ForeignKeyConstraint(['handler_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_handler_id'), 'messages', ['handler_id'], unique=False)
    op.create_index(op.f('ix_messages_product_id'), 'messages', ['product_id'], unique=False)
    op.create_index('ix_messages_status_type_created', 'messages', ['status', 'type', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_status_type_created', table_name='messages')
    op.drop_index(op.f('ix_messages_product_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_handler_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_rp_permission_id', table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('ix_products_sort', table_name='products')
    op.drop_index('ix_products_series_category_status', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_news_cat_status_pub', table_name='news')
    op.drop_table('news')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_recruit_status_category_sort', table_name='recruit')
    op.drop_table('recruit')
    op.drop_index('ix_ps_status', table_name='product_series')
    op.drop_table('product_series')
    op.drop_index('ix_pc_status', table_name='product_categories')
    op.drop_index('ix_pc_parent_id', table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index('ix_nc_status', table_name='news_categories')
    op.drop_table('news_categories')
    op.drop_index('ix_cases_status_sort', table_name='cases')
    op.drop_table('cases')
    op.drop_index('ix_banners_status_sort', table_name='banners')
    op.drop_table('banners')
    op.drop_table('about_pages')
    # ### end Alembic commands ###
